# Generated by Django 4.0.4 on 2022-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crifform',
            name='contract_columns',
            field=models.FileField(upload_to='crif/uploads/', verbose_name="Submit 'CRIFCONTRACTDATA.xlsx' File Here"),
        ),
        migrations.AlterField(
            model_name='crifform',
            name='date_of_prod',
            field=models.CharField(max_length=8, verbose_name='Production Date - 00000000'),
        ),
        migrations.AlterField(
            model_name='crifform',
            name='last_acc_date',
            field=models.CharField(max_length=8, verbose_name='Last Accounting Date - DDMMYYYY - 00000000'),
        ),
        migrations.AlterField(
            model_name='crifform',
            name='subject_columns',
            field=models.FileField(upload_to='crif/uploads/', verbose_name="Submit 'CRIFSUBJECTDATA.xlsx' File Here"),
        ),
    ]
