# Generated by Django 4.0.4 on 2022-05-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0002_alter_crifform_contract_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crifFormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_code', models.CharField(max_length=5, verbose_name='Financial Institution Code - XXXXX')),
                ('branch_code', models.CharField(max_length=7, verbose_name='Branch Code - BRANCH00')),
                ('last_acc_date', models.CharField(max_length=8, verbose_name='Last Accounting Date - DDMMYYYY - 00000000')),
                ('date_of_prod', models.CharField(max_length=8, verbose_name='Production Date - 00000000')),
                ('code', models.IntegerField(verbose_name='Code - 000')),
                ('corr_flag', models.CharField(max_length=1, verbose_name="Correction flag - '1' or ' '")),
                ('crifform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crifparser.crifform')),
            ],
            options={
                'db_table': 'Client_Info',
            },
        ),
    ]
