# Generated by Django 4.0.4 on 2022-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0003_crifforminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crifform',
            name='branch_code',
            field=models.CharField(max_length=8, verbose_name='Branch Code - BRANCH00'),
        ),
        migrations.AlterField(
            model_name='crifforminfo',
            name='branch_code',
            field=models.CharField(max_length=8, verbose_name='Branch Code - BRANCH00'),
        ),
    ]
