# Generated by Django 4.1.2 on 2022-10-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0004_alter_crifform_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crifform',
            name='contract_columns',
            field=models.FileField(upload_to='uploads/', verbose_name="Submit 'CONTRACT.xlsx' File Here"),
        ),
        migrations.AlterField(
            model_name='crifform',
            name='subject_columns',
            field=models.FileField(upload_to='uploads/', verbose_name="Submit 'SUBJECT.xlsx' File Here"),
        ),
    ]
