# Generated by Django 4.1.2 on 2022-10-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0005_alter_crifform_contract_columns_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crifform',
            table='CrifClient',
        ),
        migrations.AlterModelTable(
            name='crifforminfo',
            table='CrifClient_Info',
        ),
    ]
