# Generated by Django 4.1.2 on 2022-10-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0006_alter_crifform_table_alter_crifforminfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crifform',
            table='client',
        ),
        migrations.AlterModelTable(
            name='crifforminfo',
            table='Client_Info',
        ),
    ]
