# Generated by Django 4.1.2 on 2022-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0007_alter_crifform_table_alter_crifforminfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='crifDataMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_i_code', models.CharField(max_length=5, verbose_name='Financial Institution Code - XXXXX')),
                ('branch_code', models.CharField(max_length=8, verbose_name='Branch Code - BRANCH00')),
                ('last_acc_date', models.CharField(max_length=8, verbose_name='Last Accounting Date - DDMMYYYY - 00000000')),
                ('date_of_prod', models.CharField(max_length=8, verbose_name='Production Date - 00000000')),
                ('code', models.IntegerField(verbose_name='Code - 000')),
                ('corr_flag', models.CharField(max_length=1, verbose_name="Correction flag - '1' or ' '")),
                ('contract_columns', models.FileField(upload_to='uploads/', verbose_name="Submit 'CONTRACT.xlsx' File Here")),
                ('subject_columns', models.FileField(upload_to='uploads/', verbose_name="Submit 'SUBJECT.xlsx' File Here")),
            ],
            options={
                'db_table': 'ClientData',
            },
        ),
        migrations.DeleteModel(
            name='crifFormInfo',
        ),
    ]
