# Generated by Django 4.1.2 on 2022-10-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crifparser', '0008_crifdatamod_delete_crifforminfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crifDataMod',
        ),
    ]
